addons:
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12

dist: bionic

language: ruby
rvm:
  - 2.6.3
bundler_args: --without production

# https://travis-ci.community/t/test-against-postgres-12/6768/10
before_install:
  - sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/12/main/postgresql.conf
  - sudo cp /etc/postgresql/{9.3,12}/main/pg_hba.conf
  - sudo pg_ctlcluster 12 main restart

script:
  - bundle exec rails db:create
  - bundle exec rails db:migrate
  - bundle exec rspec -f doc
